/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fscon.h"

 int main (int argc, char *argv[])
 {
 	CLIENT *clnt;
 	int *pfd;
 	int *result;
 	LEER_result  *result_leer;	
 	int leer_nbytes;

 	if (argc < 3) 
 	{
 		printf ("Uso: %s server_host nombre_fichero\n", argv[0]);
 		exit (1);
 	}

 	clnt = clnt_create (argv[1], FSCON, CON, "udp");
 	if (clnt == NULL) 
 	{
 		clnt_pcreateerror (argv[1]);
 		exit (1);
 	}
 	else
 	{

 		/*

		CÓDIGO DE ESCRITURA

 		*/

 	}
 	exit (0);
 }