package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* sábado 7 de mayo de 2016 13H07' CEST
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
