language: java

jdk:
  - oraclejdk8

notifications:
    email:
        on_success: never
        on_failure: never
    slack: proyectoscarlos:quyUXvpLXPctdsK53REk5ypl

script:
    # Proyecto RMI
    - cd ./proyectoRMI/observador && make all && cd ../centralita && make all && cd ../cliente && make all
    - cd ../observador && make observador && cd ../centralita && make centralita
