/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "fscon.h"

bool_t
xdr_BUF (XDR *xdrs, BUF *objp)
{
	register int32_t *buf;

	 if (!xdr_bytes (xdrs, (char **)&objp->BUF_val, (u_int *) &objp->BUF_len, BUF_SIZE))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_LEER_result (XDR *xdrs, LEER_result *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->cod_error))
		 return FALSE;
	 if (!xdr_BUF (xdrs, &objp->datos))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_leer_1_argument (XDR *xdrs, leer_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->fd))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nbytes))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_escribir_1_argument (XDR *xdrs, escribir_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->fd))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nbytes))
		 return FALSE;
	 if (!xdr_BUF (xdrs, &objp->buf))
		 return FALSE;
	return TRUE;
}
