/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fscon.h"
 #include "string.h"

 int main (int argc, char *argv[])
 {
 	CLIENT *clnt;
 	int *pfd;
 	int *result;
 	int *result_escribir;	
 	int escribir_nbytes;
 	BUF datos;
 	char texto[] = "Cadena de texto";

 	if (argc < 3) 
 	{
 		printf ("Uso: %s server_host nombre_fichero\n", argv[0]);
 		exit (1);
 	}

 	clnt = clnt_create (argv[1], FSCON, CON, "udp");
 	if (clnt == NULL) 
 	{
 		clnt_pcreateerror (argv[1]);
 		exit (1);
 	}
 	else
 	{
	   /* Abre el fichero */
 		pfd = abrir_1(argv[2], clnt);
 		if (pfd == (int *) NULL) 
 		{
 			clnt_perror (clnt, "call failed");
 		}
 		else
 		{
 			printf("El descriptor es: %d \n",*pfd);
 		}

 		// Escribir en el fichero
 		escribir_nbytes = strlen(texto);

 		datos.BUF_val = texto;
 		datos.BUF_len = escribir_nbytes;

 		printf("Tamaño datos: %d \n", datos.BUF_len);
 		printf("Texto para escribir: %s", datos.BUF_val);

 		result_escribir = escribir_1(*pfd, escribir_nbytes, datos, clnt);

 		if (result_escribir == NULL) 
 		{
 			clnt_perror (clnt, "call failed");
 		}
 		else
 		{
 			printf("\nSe han escrito %d octetos \n", *result_escribir);
 		}

	   	/* Cierra el fichero previamente abierto */
 		result = cerrar_1(*pfd, clnt);

 		if (result == (int *) NULL) 
 		{
 			clnt_perror (clnt, "call failed");
 		}
 		clnt_destroy (clnt);
 	}
 	exit (0);
 }