/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fscon.h"

 int main (int argc, char *argv[])
 {
 	CLIENT *clnt;
 	int *pfd;
 	int *result;
 	LEER_result  *result_leer;	
 	int leer_nbytes;

 	if (argc < 3) 
 	{
 		printf ("Uso: %s server_host nombre_fichero\n", argv[0]);
 		exit (1);
 	}

 	clnt = clnt_create (argv[1], FSCON, CON, "udp");
 	if (clnt == NULL) 
 	{
 		clnt_pcreateerror (argv[1]);
 		exit (1);
 	}
 	else
 	{
	   /* Abre el fichero */
 		pfd = abrir_1(argv[2], clnt);
 		if (pfd == (int *) NULL) 
 		{
 			clnt_perror (clnt, "call failed");
 		}
 		else
 		{
 			printf("El descriptor es: %d\n",*pfd);
 		}

 		/*

		CÓDIGO DE ESCRITURA

 		*/

	   	/* Cierra el fichero previamente abierto */
 		result = cerrar_1(*pfd, clnt);

 		if (result == (int *) NULL) 
 		{
 			clnt_perror (clnt, "call failed");
 		}
 		clnt_destroy (clnt);
 	}
 	exit (0);
 }