package TiempoApp;


/**
* TiempoApp/TiempoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tiempo.idl
* domingo 8 de mayo de 2016 10H27' CEST
*/

public interface TiempoOperations 
{
  int getHora ();
  int getMinutos ();
  int getSegundos ();
  TiempoApp.TiempoPackage.tiempo getTiempo ();
} // interface TiempoOperations
