package TiempoApp;


/**
* TiempoApp/TiempoPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tiempo.idl
* domingo 8 de mayo de 2016 10H27' CEST
*/

public abstract class TiempoPOA extends org.omg.PortableServer.Servant
 implements TiempoApp.TiempoOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getHora", new java.lang.Integer (0));
    _methods.put ("getMinutos", new java.lang.Integer (1));
    _methods.put ("getSegundos", new java.lang.Integer (2));
    _methods.put ("getTiempo", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // TiempoApp/Tiempo/getHora
       {
         int $result = (int)0;
         $result = this.getHora ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // TiempoApp/Tiempo/getMinutos
       {
         int $result = (int)0;
         $result = this.getMinutos ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 2:  // TiempoApp/Tiempo/getSegundos
       {
         int $result = (int)0;
         $result = this.getSegundos ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 3:  // TiempoApp/Tiempo/getTiempo
       {
         TiempoApp.TiempoPackage.tiempo $result = null;
         $result = this.getTiempo ();
         out = $rh.createReply();
         TiempoApp.TiempoPackage.tiempoHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:TiempoApp/Tiempo:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Tiempo _this() 
  {
    return TiempoHelper.narrow(
    super._this_object());
  }

  public Tiempo _this(org.omg.CORBA.ORB orb) 
  {
    return TiempoHelper.narrow(
    super._this_object(orb));
  }


} // class TiempoPOA
