package TiempoApp.TiempoPackage;

/**
* TiempoApp/TiempoPackage/tiempoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tiempo.idl
* domingo 8 de mayo de 2016 10H27' CEST
*/

public final class tiempoHolder implements org.omg.CORBA.portable.Streamable
{
  public TiempoApp.TiempoPackage.tiempo value = null;

  public tiempoHolder ()
  {
  }

  public tiempoHolder (TiempoApp.TiempoPackage.tiempo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TiempoApp.TiempoPackage.tiempoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TiempoApp.TiempoPackage.tiempoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TiempoApp.TiempoPackage.tiempoHelper.type ();
  }

}
