module TiempoApp
{
    interface Tiempo
    {
        struct Tiempo {
            long hora;
            long minutos;
            long segundos;
        };
        long getHora();
        long getMinutos();
        long getSegundos();
        Tiempo getTiempo();
    };
};
