package prueba;

/**
* prueba/CalculadoraHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculadora.idl
* sábado 7 de mayo de 2016 12H22' CEST
*/

public final class CalculadoraHolder implements org.omg.CORBA.portable.Streamable
{
  public prueba.Calculadora value = null;

  public CalculadoraHolder ()
  {
  }

  public CalculadoraHolder (prueba.Calculadora initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = prueba.CalculadoraHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    prueba.CalculadoraHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return prueba.CalculadoraHelper.type ();
  }

}
