package prueba;


/**
* prueba/CalculadoraOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculadora.idl
* sábado 7 de mayo de 2016 12H22' CEST
*/

public interface CalculadoraOperations 
{
  double add (double x, double y);
  double substract (double x, double y);
  double multiply (double x, double y);
  double divide (double x, double y);
  void storeMemory (double x);
  double readMemory ();
} // interface CalculadoraOperations
