package TiempoApp;


/**
* TiempoApp/Tiempo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tiempo.idl
* domingo 8 de mayo de 2016 10H27' CEST
*/

public interface Tiempo extends TiempoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Tiempo
