package TiempoApp;


/**
* TiempoApp/TiempoPackage/tiempo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tiempo.idl
* domingo 8 de mayo de 2016 10H27' CEST
*/

public final class tiempo implements org.omg.CORBA.portable.IDLEntity
{
  public int hora = (int)0;
  public int minutos = (int)0;
  public int segundos = (int)0;

  public tiempo ()
  {
  } // ctor

  public tiempo (int _hora, int _minutos, int _segundos)
  {
    hora = _hora;
    minutos = _minutos;
    segundos = _segundos;
  } // ctor

} // class tiempo
