package TiempoApp;

/**
* TiempoApp/TiempoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tiempo.idl
* domingo 8 de mayo de 2016 10H27' CEST
*/

public final class TiempoHolder implements org.omg.CORBA.portable.Streamable
{
  public TiempoApp.Tiempo value = null;

  public TiempoHolder ()
  {
  }

  public TiempoHolder (TiempoApp.Tiempo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TiempoApp.TiempoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TiempoApp.TiempoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TiempoApp.TiempoHelper.type ();
  }

}
