package tiempoApp;


/**
* tiempoApp/TiempoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tiempo.idl
* sábado 7 de mayo de 2016 19H06' CEST
*/

public interface TiempoOperations 
{
  int getHora ();
  int getMinutos ();
  int getSegundos ();
} // interface TiempoOperations
