package tiempoApp;


/**
* tiempoApp/Tiempo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tiempo.idl
* sábado 7 de mayo de 2016 19H06' CEST
*/

public interface Tiempo extends TiempoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Tiempo
